spring:
    data:
        rest:
            basePath: /api
            defaultPageSize: 10
            maxPageSize: 100
            returnBodyOnCreate: true
            returnBodyOnUpdate: true
    datasource:
        url: ${JDBC_URL}
        username: ${JDBC_USERNAME}
        password: ${JDBC_PASSWORD}
        driverClass: com.mysql.jdbc.Driver
    jpa:
        show-sql: true
        generate-ddl: true
        hiebernate:
            ddl-auto: validate
            naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5Dialect
server:
    port: 5000
